### PR TITLE
Anomalous data for AB 19-05-2020

### PR DESCRIPTION
**Pull request by esklarski**
Since cumulative numbers shouldn't be able to go down, I assume this was a typo. 5584 fits...

Needs research.

### CODE REVIEW

**Comment by esklarski** [comment]
It is 5574 according to awkward graph provided by the AB gov't.

screenshot20200524_025300889

**Comment by jeanpaulrsoucy** [comment]
Thanks! Seems there was a typo in the original data release:

**Comment by jeanpaulrsoucy** [comment]
Thanks for spotting this! Seems there was a typo in the original data release:

https://github.com/johanley/covid-19-canada/blob/master/data/screenshots/2020-05-19_21h15mADT/ab.png

We'll fix this on our internal sheets and deploy a data update momentarily.

**Comment by giiba** [comment]
Happy to help, and thanks to all of you maintaining this data!

I've been merging the recoveries data with the JHU data to update my covid19 site:
https://esklarski.github.io/canada.covid19/

Recoveries data isn't widely available for Canada but really helps to viualize what's going on.

**Comment by esklarski** [comment]
Happy to help, and thanks to all of you maintaining this data!

I've been merging the recoveries data with the JHU data to update my covid19 site:
https://esklarski.github.io/canada.covid19/

Recoveries data isn't widely available for Canada but really helps to viualize what's going on.

**Pull request closed without merging**
